name: prettier

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nvm
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - name: Install node.js
        run: nvm install 14.17.0
      - name: Install dependencies
        run: npm install
      - name: Prettify our source code with Prettier
        run: npm run prettier
