name: prettier

on: [push]

jobs:
  build:
    # имя для отображения в интерфейсе GitHub
    name: Build
    # обязательный параметр, который указывает где будет запущена job: облачнный runner, self-hosted и т.д.
    runs-on: ubuntu-latest
    # укажем, что для этой job нам нужен специальный контейнет
    container:
      # возьмем Docker образ Node.js из публичного реестра
      image: node:14.17.0-stretch-slim
    # последовательные задачи (шаги), важно помнить, что переменные окружения не сохраняются
    # между шагами и их нужно пробрасывать, если требуется.
    steps:
      # указываем action, который будет запущен как часть job
      # В текущем случае это клонирование репозитория
      - uses: actions/checkout@v2
      # Кеширование npm
      - name: Cache dependencies
        # включаем специальный action
        uses: actions/cache@v2
        # передаем параметры
        with:
          # что кешировать (путь)
          path: ~/.npm
          # ключ кеширования (хеш)
          key: npm-${{ hashFiles('package-lock.json') }}
          # ключ для восстановления кеша
          restore-keys: npm-
      # Установка зависимостей проекта
      - name: Install dependencies
        run: npm ci --ignore-scripts
  prettier:
    needs: build
    # имя для отображения в интерфейсе GitHub
    name: prettier
    runs-on: ubuntu-latest
    container:
      # возьмем Docker образ Node.js из публичного реестра
      image: node:14.17.0-stretch-slim
    steps:
      # указываем action, который будет запущен как часть job
      # В текущем случае это клонирование репозитория
      - uses: actions/checkout@v2
      # Кеширование npm
      - name: Cache dependencies
        # включаем специальный action
        uses: actions/cache@v2
        # передаем параметры
        with:
          # что кешировать (путь)
          path: ~/.npm
          # ключ кеширования (хеш)
          key: npm-${{ hashFiles('package-lock.json') }}
          # ключ для восстановления кеша
          restore-keys: npm-
      # Установка зависимостей проекта
      - name: Install dependencies
        run: npm ci
      - name: Prettify our source code with Prettier
        run: npm run check:format
        continue-on-error: true
      - name: Check our source code with TypeScript
        run: npm run check:tsc

